
use acs;

DELETE FROM COMPONENT;
DELETE FROM COMPONENT_LINK;
DELETE FROM INGREDIENTS;
DELETE FROM MENUS;
DELETE FROM MENU_ITEMS;
DELETE FROM MENU_ITEM_COMPONENTS;
DELETE FROM MENU_ITEM_LINK;
DELETE FROM PLATING_ITEM;
DELETE FROM PLATING_ITEM_COMPONENT;
DELETE FROM PLATING_TEAM_MEMBER;
DELETE FROM PURCHASE_ORDERS;
DELETE FROM PURCHASE_ORDER_ITEMS;
DELETE FROM SHIFT_ORDERS;
DELETE FROM SUPPLIERS;
